### ISSUE TITLE
New features suggestion & Color problem feedback

### ISSUE THREAD

**Issue by YohoYang** [aka-katto/dandere2x#108] opened 2020-02-28 15:55 UTC
I tested dandere2x. Compared with waifu2x-ncnn-vulkan, dandere2x is indeed much faster, but the problems that follow are loss of picture details and color problems.
Let's talk about the color problem first. The video generated by dandere2x is inconsistent with the source. Maybe what happened when performing RGB conversion. The following example is attached.
Another problem is that the picture details are lost. After I read and understand the principle of dandere2x, I think this is an unavoidable problem. Maybe we can solve this problem through another way of thinking, maybe it can be provided as another mode of dandere2x.
We know that animated video has 24 frames per second, but the animation does not draw such a high number of frames during the production process, that is to say, for some cheaper finished animations, there may actually be only 8 different frames per second. If the exact same frames can be found and removed by the algorithm, the images that need to be processed can be further reduced.
Another idea is whether too small blocks will lead to more edge noise, and whether moving object recognition is used to process the entire moving object can make the result better (but also increase time consumption).
Thanks for reading my maybe incorrect idea. Below is the attached picture.
origin.jpg
![origin.jpg](https://i.loli.net/2020/02/28/cfeKFvyW7xokOnp.jpg)
waifu2x-ncnn-vulkan.jpg
![waifu2x-ncnn-vulkan.jpg](https://i.loli.net/2020/02/28/3QyPjb6VHfCJKqM.jpg)
dandere2x.jpg
![dandere2x.jpg](https://i.loli.net/2020/02/28/78eCUhso5imE2Nz.jpg)

**Comment by Tremeschin** [comment] 2020-02-29 01:12
> The video generated by dandere2x is inconsistent with the source. Maybe what happened when performing RGB conversion. The following example is attached.
Another problem is that the picture details are lost. After I read and understand the principle of dandere2x, I think this is an unavoidable problem. Maybe we can solve this problem through another way of thinking, maybe it can be provided as another mode of dandere2x.

I don't seem to get those color inconsistencies with either waifu2x-converter-cpp and waifu2x-ncnn-vulkan-git here on Linux. Tested with all noise levels on both waifu2x ports and didn't get this more (saturated?) color that differs the two bottom images to the first one. If I'd say where things are getting wrong are probably on internal merged images creation but we only use jpg // png plus some cv2 and numpy arrays to read, write, build the image stuff. Will keep this in mind if I can reproduce the issue.

**# # # # # # # # # # # # # # # # # # # # #**

> Another idea is whether too small blocks will lead to more edge noise, and whether moving object recognition is used to process the entire moving object can make the result better (but also increase time consumption).

Yes, you're right, small blocks tend to give some problems with the edges but I guess 20x20 block size doesn't cause much trouble with I'd say with an source resolution greater than 480p. Not much we can do here as images are saved in a fixed width and height so squares are the most "economic" image residuals to death with as something like a variable block size would decrease a lot code maintainability because the need to rewrite a lot of core stuff plus getting a full rectangle of a object that moves is far inefficient than getting those tiny blocks. Think like how integrals working by getting a smaller and smaller portion of the graph area and add up all those altogether.

**# # # # # # # # # # # # # # # # # # # # #**

> We know that animated video has 24 frames per second, but the animation does not draw such a high number of frames during the production process, that is to say, for some cheaper finished animations, there may actually be only 8 different frames per second. If the exact same frames can be found and removed by the algorithm, the images that need to be processed can be further reduced.

IIRC we already do this; calculate the MSE difference of frame N and N+1 before actually chopping and matching blocks. However because video encoding isn't perfect, calculating the MSE of two images on a low encode quality will yield _false to the eye but not internally_ non equal images. Think like a really tiny visible of TV static noise can be seen on the source file if you try hard enough or get a low quality encode as I said.

**# # # # # # # # # # # # # # # # # # # # #**

Thanks for pointing those issues and suggestions, hope I could give you a more broad view of D2X problems we have to deal with and some workarounds.

**Comment by YohoYang** [comment] 2020-02-29 04:01
First of all, thank you for such a detailed response.

# # # # # # # # # # # # # # # # # # # # #

> I don't seem to get those color inconsistencies with either waifu2x-converter-cpp and waifu2x-ncnn-vulkan-git here on Linux. Tested with all noise levels on both waifu2x ports and didn't get this more (saturated?) color that differs the two bottom images to the first one. If I'd say where things are getting wrong are probably on internal merged images creation but we only use jpg // png plus some cv2 and numpy arrays to read, write, build the image stuff. Will keep this in mind if I can reproduce the issue.

I am using windows version 1.8, and I still think that the color of dandere2x has a large deviation. This is not because of the image upload, and this problem is reproduced locally.
When I use waifu2x-ncnn-vulkan alone to process the same frame (processing pictures), I use the same model (upconv_7_anime_style_art_rgb), and the resulting color deviation will not be too big
I thought of a possibility, I modified the yaml configuration so that the frame output of ffmpeg is in png format (for theoretically less picture loss), but I checked the png file output in workspace \ default \ inputs and did not Color difference was found.
The video encoding of x264 / x265 does not use RGB as the color configuration, but uses YUV. Since there is no problem with the jpg / png colors exported by ffmpeg, the problem may occur in the color calculation during the residual calculation or the final video merge I think it is brighter than the source.

# # # # # # # # # # # # # # # # # # # # #

Two other suggestions After reading your reply, I understand the irrationality and the difficulty of implementation. Let us put these issues aside first, hoping that the color issue can be resolved first, which affects the normal use of dandere2x

**Comment by Tremeschin** [comment] 2020-02-29 04:27
Oh, totally forgot that Waifu2x do have other models than the default I use here.

The default for the Vulkan one looks like it's the models-cunet from the package I use but there's [also these](https://github.com/nihui/waifu2x-ncnn-vulkan/tree/master/models) models from nihui's repository. Gotta test 'em but first the one you use (upconv_7_anime_style_art_rgb).

Dunno what the waifu2x-converte-cpp uses by default here, looks like the waifu2x-converter-cpp only have [these](https://github.com/DeadSix27/waifu2x-converter-cpp/tree/master/models_rgb) models so it must use the one according to the noise profile I select for the denoise level?

Will test and comment the results here whenever I'm not procrastinating ( half true /s ).

**Comment by YohoYang** [comment] 2020-02-29 05:47
> Will test and comment the results here whenever I'm not procrastinating ( half true /s ).

Thanks to the test, I found some questions about the quality of processing in today's test. You can observe the picture attached below. Among them, waifu2x-ncnn-vulkan uses Waifu2x-Extension-GUI for video processing. According to the image results, dandere2x did lose some details compared to the other.
![noise.png](https://i.loli.net/2020/02/29/vMCodVgXsHOKf91.png)

**Comment by aka-katto** [comment] 2020-03-01 08:27
> > Will test and comment the results here whenever I'm not procrastinating ( half true /s ).
> 
> Thanks to the test, I found some questions about the quality of processing in today's test. You can observe the picture attached below. Among them, waifu2x-ncnn-vulkan uses Waifu2x-Extension-GUI for video processing. According to the image results, dandere2x did lose some details compared to the other.
> ![noise.png](https://camo.githubusercontent.com/e84e6ca8b98ac23c9fbf7f657b9798f7b22ccaac/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30322f32392f764d436f6456675873484f4b6639312e706e67)

Some of this is loss is result of the filters dandere2x uses. I haven't done extensive testing with it yet, but I found some better filters that may be less lossy.

**Comment by YohoYang** [comment] 2020-03-01 12:51
> Some of this is loss is result of the filters dandere2x uses. I haven't done extensive testing with it yet, but I found some better filters that may be less lossy.

Looking forward to seeing the updates, thank you for your work

**Comment by aka-katto** [comment] 2020-03-04 06:44
I'll add the color issue into a list of known things - I would have to guess it's a result of either encoding or the image library I'm using.

As for details, I'm changing the default filters used for d2x to hopefully lose less quality in certain regions. I'll update you when this happens

**Closed by aka-katto** 2020-03-04 06:44 UTC
